const NotebookActionTypes = {
  CREATE_NEW_NOTE: 'CREATE_NEW_NOTE',
  SWITCH_ADDING_NOTE: 'SWITCH_ADDING_NOTE',
  EDIT_NOTE_TITLE: 'EDIT_NOTE_TITLE',
  SELECT_CURRENT_NOTE: 'SELECT_CURRENT_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',
  UPDATE_NOTE_TITLE: 'UPDATE_NOTE_TITLE',
  UPDATE_NOTE_TEXT: 'UPDATE_NOTE_TEXT',
};

export default NotebookActionTypes;