const NotebookActionTypes = {
  CREATE_NEW_NOTE: 'CREATE_NEW_NOTE',
  SWITCH_ADDING_NOTE: 'SWITCH_ADDING_NOTE',
  SWITCH_EDITING_NOTE_TITLE: 'SWITCH_EDITING_NOTE_TITLE',
  EDIT_NOTE_TITLE: 'EDIT_NOTE_TITLE',
  SELECT_CURRENT_NOTE: 'SELECT_CURRENT_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',
  UPDATE_NOTE_TITLE: 'UPDATE_NOTE_TITLE',
  UPDATE_NOTE_TEXT: 'UPDATE_NOTE_TEXT',
  FETCH_NOTES_START: 'FETCH_NOTES_START',
  FETCH_NOTES_SUCCESS: 'FETCH_NOTES_SUCCESS',
  FETCH_NOTES_FAILURE: 'FETCH_NOTES_FAILURE',
  UPDATE_FIREBASE_START: 'UPDATE_FIREBASE_START',
  UPDATE_FIREBASE_SUCCESS: 'UPDATE_FIREBASE_SUCCESS',
  UPDATE_FIREBASE_FAILURE: 'UPDATE_FIREBASE_FAILURE',
};

export default NotebookActionTypes;